### ISSUE TITLE
Unable to integrate controller as Trait instead of Class

### ISSUE THREAD

**Issue by aloiscochard** [bowler-framework/Bowler#15]
When controllers are instantiated using mix-in instead of declaring them as class (root type isn't Controller) they are not detected and active in bowler.

Example:
http://pastie.org/2393166

Thanks a lot!

**Comment by NoelKennedy** [comment]
This is my issue too, its to do with registering super class methods:
http://groups.google.com/group/bowler-users/browse_thread/thread/7ac54e757da2a947

**Comment by wfaler** [comment]
Fixed, available in git master as well as in the 0.5-SNAPSHOT version
