### ISSUE TITLE
Scaml and Jade cannot be loaded

### ISSUE THREAD

**Issue by rschellhorn** [bowler-framework/Bowler#2]
When trying to use Scaml or Jade templates I get the following exception:

org.fusesource.scalate.InvalidSyntaxException: string matching regex `\r?\n' expected but`!' found at 1.24
    at org.fusesource.scalate.scaml.ScamlParser.parse(ScamlParser.scala:375)
    at org.fusesource.scalate.jade.JadeCodeGenerator.generate(JadeCodeGenerator.scala:38)

This bug is likely caused by the way these files are loaded from the classpath by the  com.recursivity.commons.StringInputStreamReader util, which simply concats all lines effectively stripping the newlines.

**Comment by wfaler** [comment]
Thanks for finding it and the detail provided - will be fixed with a view to push out a bugfix release in the next few days.

**Comment by wfaler** [comment]
Fixed in master and fix for core pushed into maven/sbt repos as version 0.2.1

**Comment by rschellhorn** [comment]
Thanks, works like a charm now.
